### ISSUE TITLE
Comment for all the Classes

### ISSUE THREAD

**Issue by MelineZhao** [EPFL-SV-cpp-projects/Team_8#24]

**Comment by yibnl** [comment]
You need to document every single getter. Otherwise, the Doxygen documentation will only generate the doc for the first method that follows the Doxygen comments.
- https://github.com/EPFL-SV-cpp-projects/Team_8/blob/master/src/BedgraphReader/bedgraphreader.hpp#L33
- https://github.com/EPFL-SV-cpp-projects/Team_8/blob/master/src/BedReader/bedreader.hpp#L35

**Comment by yibnl** [comment]
The documentation of the following method is missing:
- https://github.com/EPFL-SV-cpp-projects/Team_8/blob/master/src/FastaReader/fastareader.hpp#L41

**Comment by yibnl** [comment]
You need also to document the exceptions that your methods may throw. You basically need to add `@throw exception description` in your `.hpp` files.

**Comment by yibnl** [comment]
You need to decide what to do with the remark in the following comment:
- https://github.com/EPFL-SV-cpp-projects/Team_8/blob/master/src/Matrix/matrix.cpp#L157

**Comment by yibnl** [comment]
You have commented code here:
- https://github.com/EPFL-SV-cpp-projects/Team_8/blob/master/src/Matrix/matrix.cpp#L165
